---
title: "Data Cleaning"
author: "Will Hoover"
date: "2025-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library("hoopR")
library("dplyr")
library(tictoc)
library(devtools)
library(pacman)
library(ranger)
```



```{r}
shots_2025 = shots_2025 %>% mutate(TEAM_NAME = case_when(
  TEAM_NAME == "New York Knicks" ~ "NYK",
  TEAM_NAME == "Houston Rockets" ~ "HOU",
  TEAM_NAME == "Miami Heat" ~ "MIA",
  TEAM_NAME == "Toronto Raptors" ~ "TOR",
  TEAM_NAME == "Memphis Grizzlies" ~ "MEM",
  TEAM_NAME == "Denver Nuggets" ~ "DEN",
  TEAM_NAME == "Minnesota Timberwolves" ~ "MIN",
  TEAM_NAME == "Phoenix Suns" ~ "PHX",
  TEAM_NAME == "Cleveland Cavaliers" ~ "CLE",
  TEAM_NAME == "New Orleans Pelicans" ~ "NOP",
  TEAM_NAME == "Golden State Warriors" ~ "GSW",
  TEAM_NAME == "Milwaukee Bucks" ~ "MIL",
  TEAM_NAME == "Orlando Magic" ~ "ORL",
  TEAM_NAME == "Portland Trail Blazers" ~ "POR",
  TEAM_NAME == "Washington Wizards" ~ "WAS",
  TEAM_NAME == "LA Clippers" ~ "LAC",
  TEAM_NAME == "Charlotte Hornets" ~ "CHA",
  TEAM_NAME == "Chicago Bulls" ~ "CHI",
  TEAM_NAME == "Atlanta Hawks" ~ "ATL",
  TEAM_NAME == "San Antonio Spurs" ~ "SAS",
  TEAM_NAME == "Brooklyn Nets" ~ "BKN",
  TEAM_NAME == "Philadelphia 76ers" ~ "PHI",
  TEAM_NAME == "Indiana Pacers" ~ "IND",
  TEAM_NAME == "Boston Celtics" ~ "BOS",
  TEAM_NAME == "Dallas Mavericks" ~ "DAL",
  TEAM_NAME == "Sacramento Kings" ~ "SAC",
  TEAM_NAME == "Oklahoma City Thunder" ~ "OKC",
  TEAM_NAME == "Los Angeles Lakers" ~ "LAL",
  TEAM_NAME == "Utah Jazz" ~ "UTA",
  TEAM_NAME == "Detroit Pistons" ~ "DET"
)) 
shots_2025
```

```{r}
cols_num = c("GAME_ID", "GAME_EVENT_ID", "PLAYER_ID", "TEAM_ID", "PERIOD", "SHOT_DISTANCE", "LOC_X", "LOC_Y", "SHOT_ATTEMPTED_FLAG","SHOT_MADE_FLAG", "MINUTES_REMAINING", "SECONDS_REMAINING")
shots_2025[cols_num] <- sapply(shots_2025[cols_num],as.numeric)
shots_2025
```

```{r}
shots_2025 = shots_2025 %>% 
  mutate(OPPOSING_TEAM_NAME = ifelse(TEAM_NAME == HTM, VTM, HTM)) %>% 
  relocate(OPPOSING_TEAM_NAME, .after = TEAM_NAME)
shots_2025
```

```{r}
shots_2025 = shots_2025 %>%
  mutate(QUARTER_TIME_LEFT = MINUTES_REMAINING * 60 + SECONDS_REMAINING) %>%
  mutate(GAME_TIME_LEFT = case_when(
    PERIOD <= 4 ~ (4 - PERIOD) * 12 * 60 + MINUTES_REMAINING * 60 + SECONDS_REMAINING,
    PERIOD %in% c(5, 6, 7, 8) ~ MINUTES_REMAINING * 60 + SECONDS_REMAINING
  )) %>% relocate(QUARTER_TIME_LEFT, .after = SECONDS_REMAINING) %>%
  relocate(GAME_TIME_LEFT, .after = QUARTER_TIME_LEFT)
shots_2025 
```


```{r}
nba_standings <- tribble(
  ~TEAM_NAME, ~W, ~L, ~WinPct,
  "CLE", 64, 18, 0.780,
  "BOS", 61, 21, 0.744,
  "NYK", 51, 31, 0.622,
  "IND", 50, 32, 0.610,
  "MIL", 48, 34, 0.585,
  "DET", 44, 38, 0.537,
  "ORL", 41, 41, 0.500,
  "ATL", 40, 42, 0.488,
  "CHI", 39, 43, 0.476,
  "MIA", 37, 45, 0.451,
  "TOR", 30, 52, 0.366,
  "BKN", 26, 56, 0.317,
  "PHI", 24, 58, 0.293,
  "CHA", 19, 63, 0.232,
  "WAS", 18, 64, 0.220,
  "OKC", 68, 14, 0.829,
  "HOU", 52, 30, 0.634,
  "LAL", 50, 32, 0.610,
  "DEN", 50, 32, 0.610,
  "LAC", 50, 32, 0.610,
  "MIN", 49, 33, 0.598,
  "GSW", 48, 34, 0.585,
  "MEM", 48, 34, 0.585,
  "SAC", 40, 42, 0.488,
  "DAL", 39, 43, 0.476,
  "PHX", 36, 46, 0.439,
  "POR", 36, 46, 0.439,
  "SAS", 34, 48, 0.415,
  "NOP", 21, 61, 0.256,
  "UTA", 17, 65, 0.207
)
nba_standings
```


