---
title: "STAT 479 project codes"
author: "Roy Son"
date: "2025-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("hoopR")
library("dplyr")
library(stringr)
library(tictoc)
library(devtools)
library(pacman)
```

```{r}
shots = shots_2025 %>%
  select(PLAYER_NAME, TEAM_NAME, SHOT_DISTANCE, SHOT_TYPE, SHOT_ZONE_BASIC, PTS, SHOT_MADE_FLAG)
```


###codes for total expected points by team 
```{r}
Team_abbreviation = c( "Atlanta Hawks" = "ATL", "Boston Celtics" = "BOS", "Brooklyn Nets" = "BKN",
  "Charlotte Hornets" = "CHA", "Chicago Bulls" = "CHI", "Cleveland Cavaliers" = "CLE",
  "Dallas Mavericks" = "DAL", "Denver Nuggets" = "DEN", "Detroit Pistons" = "DET",
  "Golden State Warriors" = "GSW", "Houston Rockets" = "HOU", "Indiana Pacers" = "IND",
  "LA Clippers" = "LAC", "Los Angeles Lakers" = "LAL", "Memphis Grizzlies" = "MEM",
  "Miami Heat" = "MIA", "Milwaukee Bucks" = "MIL", "Minnesota Timberwolves" = "MIN",
  "New Orleans Pelicans" = "NOP", "New York Knicks" = "NYK", "Oklahoma City Thunder" = "OKC",
  "Orlando Magic" = "ORL", "Philadelphia 76ers" = "PHI", "Phoenix Suns" = "PHX",
  "Portland Trail Blazers" = "POR", "Sacramento Kings" = "SAC", "San Antonio Spurs" = "SAS",
  "Toronto Raptors" = "TOR", "Utah Jazz" = "UTA", "Washington Wizards" = "WAS")

shots = shots %>%
  mutate(SHOT_DISTANCE = as.numeric(SHOT_DISTANCE),
         team_abbreviation = Team_abbreviation[TEAM_NAME],
         Points_rule = case_when(
           SHOT_MADE_FLAG == 1 & SHOT_TYPE == "3PT Field Goal" ~ 3,
           SHOT_MADE_FLAG == 1 & SHOT_TYPE == "2PT Field Goal" ~ 2,
           TRUE ~ 0
         ))

shots %>% 
  arrange(desc(SHOT_DISTANCE))

shots_by_ft = shots %>%
  filter(!is.na(SHOT_DISTANCE)) %>%
  mutate(distance_ft = floor(SHOT_DISTANCE))

league_average = shots_by_ft %>%
  group_by(distance_ft, SHOT_TYPE)%>%
  summarize(
    attempt_league = n(),
    made_shots_league = sum(SHOT_MADE_FLAG == 1, na.rm = TRUE),
    fg_percentage_league = attempt_league / made_shots_league, 
    expected_points_league = mean(Points_rule, na.rm = TRUE)
  )

scored_shots = shots_by_ft %>%
  left_join(league_average %>%
              select(distance_ft, SHOT_TYPE, expected_points_league),
            by = c("distance_ft", "SHOT_TYPE"))%>%
  mutate(expected_goal = expected_points_league)

Expected_vs_Actual = scored_shots %>%
  group_by(TEAM_NAME)%>%
  summarize(
    expected_points = sum(expected_goal, na.rm = TRUE),
    actual_points = sum(Points_rule, naa.rm = TRUE),
    number_of_shots = n(),
    .groups = "drop"
  )%>%mutate(residual = actual_points - expected_points)


ggplot(Expected_vs_Actual,
       aes(x = reorder(TEAM_NAME, residual),
           y = residual,
           fill = residual > 0))+
  geom_col()+
  coord_flip()+
  labs(title = "Residuals(Actual - Expected) by Team",xlab = "Team", ylab = "Residual Points")


ggplot(Expected_vs_Actual,
       aes(x = reorder(TEAM_NAME, expected_points),
           y = expected_points,
           fill = expected_points))+
  geom_col()+
  coord_flip()+
  labs(title = "Total Expected Points by Team",
       x = "Team",
       y = "Expected Total Points")+
  theme_minimal()
  
```


###just added Shot Zone Basic from the previeous version. 
```{r}
league_avearage_2.0 = shots_by_ft %>%
  group_by(distance_ft, SHOT_ZONE_BASIC, SHOT_TYPE)%>%
  summarize(
    attempt_league = n(),
    made_shots_league = sum(SHOT_MADE_FLAG == 1, na.rm = TRUE),
    fg_percentage_league = attempt_league / made_shots_league, 
    expected_points_league = mean(Points_rule, na.rm = TRUE)
  )
  
scored_shots_2.0 = shots_by_ft %>%
  left_join(league_avearage_2.0 %>%
              select(distance_ft, SHOT_ZONE_BASIC, SHOT_TYPE, expected_points_league),
            by = c("distance_ft", "SHOT_ZONE_BASIC", "SHOT_TYPE")) %>%
  mutate(expected_goal = expected_points_league)

Expected_vs_Actual_2.0 = scored_shots_2.0 %>%
  group_by(TEAM_NAME)%>%
  summarize( 
    expected_points = sum(expected_goal, na.rm = TRUE),
    actual_points = sum(Points_rule, naa.rm = TRUE),
    number_of_shots = n(),
    .groups = "drop"
  )%>%mutate(residual = actual_points - expected_points)

ggplot(Expected_vs_Actual_2.0,
       aes(x = reorder(TEAM_NAME, residual),
           y = residual,
           fill = residual > 0))+
  geom_col()+
  coord_flip()+
  labs(title = "Residuals(Actual - Expected) by Team",xlab = "Team", ylab = "Residual Points")


ggplot(Expected_vs_Actual_2.0,
       aes(x = reorder(TEAM_NAME, expected_points),
           y = expected_points,
           fill = expected_points))+
  geom_col()+
  coord_flip()+
  labs(title = "Total Expected Points by Team",
       x = "Team",
       y = "Expected Total Points")+
  theme_minimal()
```

###For Expected defense 
```{r}
Team_abbreviation = c( "Atlanta Hawks" = "ATL", "Boston Celtics" = "BOS", "Brooklyn Nets" = "BKN",
  "Charlotte Hornets" = "CHA", "Chicago Bulls" = "CHI", "Cleveland Cavaliers" = "CLE",
  "Dallas Mavericks" = "DAL", "Denver Nuggets" = "DEN", "Detroit Pistons" = "DET",
  "Golden State Warriors" = "GSW", "Houston Rockets" = "HOU", "Indiana Pacers" = "IND",
  "LA Clippers" = "LAC", "Los Angeles Lakers" = "LAL", "Memphis Grizzlies" = "MEM",
  "Miami Heat" = "MIA", "Milwaukee Bucks" = "MIL", "Minnesota Timberwolves" = "MIN",
  "New Orleans Pelicans" = "NOP", "New York Knicks" = "NYK", "Oklahoma City Thunder" = "OKC",
  "Orlando Magic" = "ORL", "Philadelphia 76ers" = "PHI", "Phoenix Suns" = "PHX",
  "Portland Trail Blazers" = "POR", "Sacramento Kings" = "SAC", "San Antonio Spurs" = "SAS",
  "Toronto Raptors" = "TOR", "Utah Jazz" = "UTA", "Washington Wizards" = "WAS")




shots_defense = shots_2025 %>%
  select(GAME_ID, HTM, VTM, PLAYER_NAME, TEAM_NAME, SHOT_DISTANCE, SHOT_TYPE,
         SHOT_ZONE_BASIC, SHOT_MADE_FLAG, PTS)%>%
  mutate(
    SHOT_DISTANCE = as.numeric(SHOT_DISTANCE),
    Points_rule = case_when(
      SHOT_MADE_FLAG == 1 & SHOT_TYPE == "3PT Field Goal" ~ 3,
      SHOT_MADE_FLAG == 1 & SHOT_TYPE == "2PT Field Goal" ~ 2,
      TRUE ~ 0
         ),
    team_abbreviation = Team_abbreviation[TEAM_NAME],
    Opponents = case_when(
      team_abbreviation == HTM ~ VTM,
      team_abbreviation == VTM ~ HTM,
      TRUE ~ NA_character_
    ))

shots_by_ft_defense = shots_defense%>%
  filter(!is.na(SHOT_DISTANCE))%>%
  mutate(distance_ft = floor(SHOT_DISTANCE))

league_average_defense = shots_by_ft_defense %>%
  group_by(distance_ft, SHOT_TYPE)%>%
  summarize(
    attempt_league = n(),
    made_shots_league = sum(SHOT_MADE_FLAG == 1, na.rm = TRUE),
    fg_percentage_league = attempt_league / made_shots_league, 
    expected_points_league = mean(Points_rule, na.rm = TRUE)
  )

scored_shots_defense = shots_by_ft_defense %>%
  left_join(league_average_defense %>%
              select(distance_ft, SHOT_TYPE, expected_points_league),
            by = c("distance_ft","SHOT_TYPE")) %>%
  mutate(expected_goal = expected_points_league)

Expected_vs_Actual_defense = scored_shots_defense %>%
  group_by(Opponents)%>%
  summarize(
    expected_points_allowed = sum(expected_goal, na.rm = TRUE),
    actual_points_allowed = sum(Points_rule, naa.rm = TRUE),
    number_of_shots_faced = n(),
    .groups = "drop"
  )%>% mutate(residuals_allowed = actual_points_allowed - expected_points_allowed )


ggplot(Expected_vs_Actual_defense,
       aes(x = reorder(Opponents, residuals_allowed),
           y = residuals_allowed,
           fill = residuals_allowed > 0))+
  geom_col()+
  coord_flip()+
  labs(title = "Residuals allowed(Actual - Expected) by Team",xlab = "Team", ylab = "Residual Points Allowed")


ggplot(Expected_vs_Actual_defense,
       aes(x = reorder(Opponents, expected_points_allowed),
           y = expected_points_allowed,
           fill = expected_points_allowed))+
  geom_col()+
  coord_flip()+
  labs(title = "Total Expected Points allowed by Team",
       x = "Team",
       y = "Expected Total Points Allowed")+
  theme_minimal()

```


###Expected Combined Points by Teams 
```{r}
Expected_vs_Actual_2.0 = Expected_vs_Actual_2.0 %>%
  mutate(Team_abbreviation = Team_abbreviation[TEAM_NAME])


Offense_and_Defense = Expected_vs_Actual_2.0 %>%
  select(TEAM_NAME, Team_abbreviation,
         expected_points_scored = expected_points,
         actual_points_scored = actual_points,
         resiudal_scored = residual)%>%
  left_join(
    Expected_vs_Actual_defense%>%
      select(Opponents, 
             expected_points_allowed,
             actual_points_allowed,
             residuals_allowed),
    by = c("Team_abbreviation" = "Opponents")) %>%
      mutate(
        expected_combined_points = expected_points_scored - expected_points_allowed,
        actual_combined_points = actual_points_scored - actual_points_allowed,
        residual_combined = resiudal_scored - residuals_allowed
      )
  
ggplot(Offense_and_Defense, 
       aes(x = reorder(TEAM_NAME, residual_combined),
           y = residual_combined, 
           fill = residual_combined > 0))+
  geom_col()+
  coord_flip()+
  labs(title = "Combined (Offesne - Defense) Residuals by Team",
       x = "Team",
       y = "Net Residual Points")+
  theme_minimal()

ggplot(Offense_and_Defense, 
       aes(x = reorder(TEAM_NAME, expected_combined_points),
           y =  expected_combined_points,
           fill = expected_combined_points))+
  geom_col()+
  coord_flip()+
  labs(title = "Total Expected Combined Points by Teams",
       x = "Team",
       y = "Expected Combined points")
```

```{r}
nba_standings = tribble(
  ~TEAM_NAME, ~W, ~L, ~WinPct,
  "CLE", 64, 18, 0.780,
  "BOS", 61, 21, 0.744,
  "NYK", 51, 31, 0.622,
  "IND", 50, 32, 0.610,
  "MIL", 48, 34, 0.585,
  "DET", 44, 38, 0.537,
  "ORL", 41, 41, 0.500,
  "ATL", 40, 42, 0.488,
  "CHI", 39, 43, 0.476,
  "MIA", 37, 45, 0.451,
  "TOR", 30, 52, 0.366,
  "BKN", 26, 56, 0.317,
  "PHI", 24, 58, 0.293,
  "CHA", 19, 63, 0.232,
  "WAS", 18, 64, 0.220,
  "OKC", 68, 14, 0.829,
  "HOU", 52, 30, 0.634,
  "LAL", 50, 32, 0.610,
  "DEN", 50, 32, 0.610,
  "LAC", 50, 32, 0.610,
  "MIN", 49, 33, 0.598,
  "GSW", 48, 34, 0.585,
  "MEM", 48, 34, 0.585,
  "SAC", 40, 42, 0.488,
  "DAL", 39, 43, 0.476,
  "PHX", 36, 46, 0.439,
  "POR", 36, 46, 0.439,
  "SAS", 34, 48, 0.415,
  "NOP", 21, 61, 0.256,
  "UTA", 17, 65, 0.207
)
```



### codes made for Pythagorean win percentage. 
```{r}

Expected_Offense = Expected_vs_Actual_2.0 %>% 
  mutate(Team_abbreviation = Team_abbreviation[TEAM_NAME])%>% 
  select(TEAM_NAME, Team_abbreviation, expected_points_scored = expected_points) 


Expected_Defense = Expected_vs_Actual_defense %>% 
  rename(Team_abbreviation = Opponents)%>% select(Team_abbreviation, expected_points_allowed) 

Games_per_team = shots_2025 %>% 
  select(TEAM_NAME, GAME_ID)%>% 
  distinct()%>% 
  count(TEAM_NAME, name = "games") 

pythagorean_win = Expected_Offense %>% 
  left_join(Expected_Defense, by = "Team_abbreviation")%>% 
  left_join(Games_per_team, by = "TEAM_NAME")%>% 
  mutate(expected_points = expected_points_scored / games, expected_points_against = expected_points_allowed / games, pythagorean_win_percentage = (expected_points^1.83) / ((expected_points^1.83)+(expected_points_against^1.83)), expected_wins = pythagorean_win_percentage * games, expected_losses = games - expected_wins)

pythagorean_win = pythagorean_win %>%
  mutate(expected_wins = round(expected_wins),
         expected_losses = round(expected_losses))
```


### Using Brier and log loss to see the acuracy
```{r}
brier = function(y, phat){
  return(mean((y-phat)^2))
}

log_loss = function(y, phat){
  if(any(phat < 1e-12)) phat[phat < 1e-12] <- 1e-12
  if(any(phat > 1-1e-12)) phat[phat > 1-1e-12] <- 1-1e-12
  return(-1 * mean( y * log(phat) + (1-y) * log(1-phat)))
}

Comparison = pythagorean_win %>%
  select(TEAM_NAME, Team_abbreviation, pythagorean_win_percentage) %>%
  left_join(nba_standings, by = c("Team_abbreviation" = "TEAM_NAME"))%>%
  rename(true_win_percentage = WinPct, predicted_win_percentage = pythagorean_win_percentage)

brier_comparison = brier(Comparison$true_win_percentage, Comparison$predicted_win_percentage)
brier_comparison

log_loss_season = log_loss(Comparison$true_win_percentage, Comparison$predicted_win_percentage)
log_loss_season

```



###shows the accuracey for the brier and log loss score 
```{r}
set.seed(5)

simulate_score = function(df, games_per_team = 82){
  game_level = df %>%
    tidyr::uncount(games_per_team) %>%
    mutate(actual = rbinom(n(), size = 1, prob = true_win_percentage),
           prediction = pmin(pmax(predicted_win_percentage, 1e-12),1-1e-12),
           each_brier = (prediction-actual)^2,
           each_log_loss = -(actual * log(prediction)+(1-actual)* log(1-prediction))
           )
  tibble(mean_brier = mean(game_level$each_brier),
         mean_log_loss = mean(game_level$each_log_loss))}

results = bind_rows(
  simulate_score(Comparison),
  simulate_score(Comparison),
  simulate_score(Comparison))

results %>% summarize(average_brier = mean(mean_brier),
                      average_log_loss = mean(mean_log_loss))

```




