---
title: "The project 2"
author: "Roy Son"
date: "2025-11-02"
output: html_document
---

```{r setup, include = FALSE}
library(BradleyTerry2)
library(tidyverse)
```


```{r}
season_2024 = read_csv("games_with_pitchers.csv")

season_2024 = season_2024 %>%
  arrange(Date, row_number())
```


```{r}
Bradley_Terry = season_2024 %>%
  transmute(
    home.team = factor(Home_Tm),
    away.team = factor(Away_Tm),
    home.win = as.integer(Home_Winner),
    away.win = as.integer(Away_Winner),
    at.home_home = 1,
    at.home_away = 0,
    era_difference_raw = Home_Pitcher_ERA - Away_Pitcher_ERA
  )%>% 
  filter(!is.na(era_difference_raw)) %>%
  mutate(era_difference = era_difference_raw - mean(era_difference_raw, na.rm=TRUE))
```


```{r}
data_frame = data.frame(
  home.win = Bradley_Terry$home.win,
  away.win = Bradley_Terry$away.win
)

data_frame$home.team = data.frame(
  team = Bradley_Terry$home.team,
  at.home = 1,
  era = + Bradley_Terry$era_difference/2
)

data_frame$away.team = data.frame(
  team = Bradley_Terry$away.team,
  at.home = 0,
  era = - Bradley_Terry$era_difference/2
)
```


```{r}
reference_team = levels(Bradley_Terry$home.team)[4]

fit_0 = BTm(
  outcome = cbind(home.win, away.win),
  player1 = home.team,
  player2 = away.team,
  formula = ~ team + at.home,
  refcat = reference_team,
  id = "team",
  data = data_frame
)

summary(fit_0)
```


```{r}
fit = BTm(
  outcome = cbind(home.win, away.win),
  player1 = home.team,
  player2 = away.team,
  formula = ~ team + at.home + era,
  refcat = reference_team,
  id = "team",
  data = data_frame
)

summary(fit)
```

```{r}
team_abilities = BradleyTerry2::BTabilities(fit) %>%
  as.data.frame()%>%
  rownames_to_column("Team") %>%
  arrange(desc(ability))
team_abilities 

coefficient = coef(fit)

home_adventage = unname(coefficient["at.home"])
```


```{r}
rank = team_abilities %>%
  mutate(
    Rank = rank(-ability, ties.method = "min"),
    low = ability - 1.96 * `s.e.`,
    high = ability + 1.96 * `s.e.`,
  ) %>%
  select(Rank, Team, ability, low, high,`s.e.`)
```


```{r}
home_ability = team_abilities %>%
  select(Team, ability) %>%
  rename(home.team = Team, ability_home = ability)

away_ability = team_abilities %>%
  select(Team, ability) %>%
  rename(away.team = Team, ability_away = ability)

evaluation = Bradley_Terry  %>%
  mutate(row_id = row_number()) %>%
  left_join(home_ability, by = "home.team") %>%
  left_join(away_ability, by = "away.team") %>%
  mutate(
    linear_predictor = (ability_home - ability_away) + home_adventage * 1,
    probability_home_team = 1/ (1 + exp(-linear_predictor)),
    y = home.win
  )
```



```{r}
brier = function(y, phat){
  return(mean( (y - phat)^2 ))
}

log_loss = function(y, phat){
  if(any(phat < 1e-12)) phat[phat < 1e-12] <- 1e-12
  if(any(phat > 1-1e-12)) phat[phat > 1-1e-12] <- 1-1e-12
  return(-1 * mean( y * log(phat) + (1-y) * log(1-phat)))
}

brier(evaluation$home.win, evaluation$probability_home_team)
log_loss(evaluation$home.win, evaluation$probability_home_team)
```




```{r}
expected_wins_home = evaluation %>%
  group_by(home.team) %>%
  summarize(expected_home_wins = sum(probability_home_team), .groups = "drop")

expected_wins_away = evaluation %>%
  mutate(paway = 1 - probability_home_team) %>%
  group_by(away.team) %>%
  summarize(expected_away_wins = sum(paway),.groups = "drop")

expected_wins = expected_wins_home %>%
  full_join(expected_wins_away, by = c("home.team" = "away.team")) %>%
  transmute(
    Team = home.team,
    Expected_wins = coalesce(expected_home_wins, 0) + coalesce(expected_away_wins,0)
  )

actual_wins = season_2024 %>%
  mutate(Winner = as.character(Winner)) %>%
  count(Winner, name = "Actual_Wins") %>%
  rename(Team = Winner)

expected_vs_actual_wins = expected_wins %>%
  full_join(actual_wins, by = "Team") %>%
  replace_na(list(Expected_wins=0, Actual_Wins = 0))%>%
  mutate(
    Expected_Wins = round(Expected_wins,0),
    Actual_Wins = round(Actual_Wins,0)
  )%>%
  select(-Expected_wins)%>%
  arrange(desc(Expected_Wins))%>%
  print(n=30)
```

```{r}
ggplot(rank, aes(x = reorder(Team, ability), y = ability))+
  geom_point()+
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.2)+
  coord_flip()+
  labs(
    title = "Bradley-Terry Team Abilities",
    x = "Team",
    y = "Ability"
  )+theme_minimal()
```


`
