---
title: "BaseballR Entry"
author: "Will Hoover"
date: "2025-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(baseballr)
library(BradleyTerry2)
```


# Building main dataframe

```{r}
mil = as.data.frame(bref_team_results("MIL", 2024))
mil
```


```{r}
opponents = unique(mil$Opp)
opponents
```
```{r}
teams <- c("NYM", "MIN", "SEA", "CIN", "BAL", "SDP", "STL", "PIT", "NYY", "TBR", 
           "CHC", "KCR", "HOU", "MIA", "BOS", "CHW", "PHI", "DET", "TOR", "LAA", 
           "TEX", "COL", "LAD", "WSN", "ATL", "CLE", "OAK", "SFG", "ARI", "MIL")

all_teams_df <- data.frame()  # initialize empty dataframe

for(team in teams) {
  team_data <- as.data.frame(bref_team_results(team, 2024))
  all_teams_df <- rbind(all_teams_df, team_data)
}
```

```{r}
all_teams_df
```



```{r}
all_teams_df = all_teams_df %>% mutate (Winner = ifelse(Result %in% c("W", "W-wo"), Tm, Opp), 
                                        Loser = ifelse(Result %in% c("L", "L-wo"), Tm, Opp) )
all_teams_df
```

```{r}
save(all_teams_df, file = "all_teams_df.RData")
```



```{r}
all_teams_df
```


```{r}
# Keep only the unique teams, as each row is there twice, one for home perspective, one from away
all_teams_df_unique <- all_teams_df %>%
  rowwise() %>%
  mutate(game_id = paste(sort(c(Tm, Opp)), collapse = "_")) %>%
  ungroup() %>%
  distinct(Date, game_id, .keep_all = TRUE) %>% relocate(Loser, .before = Result) %>% relocate(Winner, .after = Opp)
all_teams_df_unique
```


```{r}
unique(all_teams_df$Result)
```


```{r}
# Identify Home/Away Teams
all_teams_df_unique = all_teams_df_unique %>% mutate(Home_Tm = ifelse(H_A == "H", Tm, Opp), Away_Tm = ifelse(H_A == "A", Tm, Opp), )
all_teams_df_unique
```

```{r}
# Identify if Home/Away Team Won
all_teams_df_unique <- all_teams_df_unique %>%
  mutate(
    Home_Winner = ifelse(Winner == Home_Tm, 1, 0),
    Away_Winner = ifelse(Winner == Away_Tm, 1, 0)
  )
```


```{r}
# Visualize how many runs are scored by the home/away team, rename winning/losing pitcher for confusion sake
all_teams_df_unique = all_teams_df_unique %>%
  mutate(
    Home_Runs = ifelse(H_A == "H", R, RA),
    Away_Runs = ifelse(H_A == "A", R, RA)
  ) %>% rename(Win_Pitch = Win, Loss_Pitch = Loss)
all_teams_df_unique
```

```{r}
# Select only relevant variables
game_log = all_teams_df_unique %>% select(Gm, Date, Home_Tm, Away_Tm, Home_Winner, Away_Winner, Home_Runs, Away_Runs, Winner, Loser, Win_Pitch, Loss_Pitch, Save, cLI)
game_log
```


### ONLY DO THIS IF WE ACTUALLY NEED PITCH BY PITCH DATA, RUN ONCE THEN SAVE DATAFRAME

```{r}
## Code modified from Bill Petti's original annual Statcast scraper:
## Main change is in the column names of the fielders

annual_statcast_query <- function(season) {
  
  data_base_column_types <- 
    readr::read_csv("https://app.box.com/shared/static/q326nuker938n2nduy81au67s2pf9a3j.csv")
  
  dates <- 
    seq.Date(as.Date(paste0(season, '-03-01')),
             as.Date(paste0(season, '-12-01')), 
             by = '4 days')
  
  date_grid <- 
    tibble::tibble(start_date = dates, 
                   end_date = dates + 3)
  
  safe_savant <- 
    purrr::safely(baseballr::scrape_statcast_savant)
  
  payload <- 
    purrr::map(.x = seq_along(date_grid$start_date),
               ~{message(paste0('\nScraping week of ', date_grid$start_date[.x], '...\n'))
                 payload <- 
                   safe_savant(start_date = date_grid$start_date[.x], 
                               end_date = date_grid$end_date[.x], 
                               type = 'pitcher')
                 return(payload)
               })
  
  payload_df <- purrr::map(payload, 'result')
  
  number_rows <- 
    purrr::map_df(.x = seq_along(payload_df),
                  ~{number_rows <- 
                    tibble::tibble(week = .x, 
                                   number_rows = length(payload_df[[.x]]$game_date))
                  }) %>%
    dplyr::filter(number_rows > 0) %>%
    dplyr::pull(week)
  
  payload_df_reduced <- payload_df[number_rows]
  
  payload_df_reduced_formatted <- 
    purrr::map(.x = seq_along(payload_df_reduced), 
               ~{cols_to_transform <- 
                 c("pitcher", "fielder_2", "fielder_3",
                   "fielder_4", "fielder_5", "fielder_6", "fielder_7",
                   "fielder_8", "fielder_9")
               df <- 
                 purrr::pluck(payload_df_reduced, .x) %>%
                 dplyr::mutate_at(.vars = cols_to_transform, as.numeric) %>%
                 dplyr::mutate_at(.vars = cols_to_transform, function(x) {ifelse(is.na(x), 999999999, x)})
               character_columns <- 
                 data_base_column_types %>%
                 dplyr::filter(class == "character") %>%
                 dplyr::pull(variable)
               numeric_columns <- 
                 data_base_column_types %>%
                 dplyr::filter(class == "numeric") %>%
                 dplyr::pull(variable)
               integer_columns <- 
                 data_base_column_types %>%
                 dplyr::filter(class == "integer") %>%
                 dplyr::pull(variable)
               df <- 
                 df %>%
                 dplyr::mutate_if(names(df) %in% character_columns, as.character) %>%
                 dplyr::mutate_if(names(df) %in% numeric_columns, as.numeric) %>%
                 dplyr::mutate_if(names(df) %in% integer_columns, as.integer)
               return(df)
               })
  
  combined <- payload_df_reduced_formatted %>%
    dplyr::bind_rows()
  
  return(combined)
}
```


```{r}
raw_statcast2024 <- annual_statcast_query(2024)
```

```{r}
library(tidyverse)
raw_statcast2024 <- annual_statcast_query(2024)
save(raw_statcast2024, file = "raw_statcast2024.RData")
```


```{r}
load("raw_statcast2024.RData")
```


```{r}
raw_statcast2024
```






# Hockey Testing for fitting BTM
```{r}
wd1hockey_2024_2025 <- readr::read_csv(file = "wd1hockey_2024_2025.csv")
```




```{r}
wd1hockey_2024_2025 |>
  dplyr::filter(HomeScore == OppScore) |>
  dplyr::select(Opponent, OppScore, Home, HomeScore, Notes) |>
  dplyr::slice_head(n=5)
```

```{r}
team_abbr <- readr::read_csv(file = "wd1hockey_teams.csv")
```

```{r}
get_home_winner <- 
  function(Home_abbr, HomeScore, Opp_abbr, OppScore, Notes)
{
  home_winner <- NA
  if(HomeScore > OppScore) home_winner <- 1
  else if(HomeScore < OppScore) home_winner <- 0
  else{
    if(!is.na(Notes) & grepl("SO", Notes)){
      winner <- 
        stringr::str_split(string = Notes, pattern = " wins")[[1]][1]
      if(winner == Home_abbr) home_winner <- 1
      else if(winner == Opp_abbr) home_winner <- 0
    }
  }
  return(home_winner)
}
```


```{r}
wd1hockey_2024_2025 <-
  wd1hockey_2024_2025 |>
  dplyr::mutate(
    HomeScore = as.integer(HomeScore),
    OppScore = as.integer(OppScore)) |>
  dplyr::left_join(y = team_abbr |> dplyr::rename(Home_abbr = abbr, Home = team),
                   by = "Home") |>
  dplyr::left_join(y = team_abbr |> dplyr::rename(Opp_abbr = abbr, Opponent = team),
                   by = "Opponent") |>
  dplyr::rowwise() |>
  dplyr::mutate(
    Home_Winner = 
      get_home_winner(Home_abbr, HomeScore, Opp_abbr, OppScore, Notes)) |>
  dplyr::ungroup() |>
  dplyr::mutate(Opp_Winner = 1-Home_Winner)
```

```{r}
wd1hockey_2024_2025
```
