---
title: "Project 2 of the Roy Son"
author: "Roy Son"
date: "2025-11-06"
output: html_document
---

```{r}
library(tidyverse)
devtools::install_github("hturner/BradleyTerry2")
library(BradleyTerry2)
```


```{r}
games_with_pitchers <- read.csv("games_with_pitchers.csv")
games_with_pitchers$Date = as.Date(games_with_pitchers$Date)
```


```{r}
brier <- function(y, phat){
  return(mean( (y - phat)^2 ))
}

logloss <- function(y, phat){
  
  if(any(phat < 1e-12)) phat[phat < 1e-12] <- 1e-12
  if(any(phat > 1-1e-12)) phat[phat > 1-1e-12] <- 1-1e-12
  return(-1 * mean( y * log(phat) + (1-y) * log(1-phat)))
}
```


```{r}
set.seed(50)

n = nrow(games_with_pitchers)

cv_log = data.frame()

for(r in 1:100){
  train_idx = sample(1:n, size = floor(0.75*n), replace = FALSE)
  train_df = games_with_pitchers[train_idx,]
  test_df = games_with_pitchers[-train_idx,]
  unik_teams = sort(unique(c(train_df$Home_Tm, train_df$Away_Tm)))
  
  results_train = train_df %>%
    rename(home_team = Home_Tm, away_team = Away_Tm) %>% 
  mutate(
    home_team = factor(home_team, levels = unik_teams), 
    away_team = factor(away_team,levels = unik_teams),
    home_athome = 1,
    away_athome = 0)
  
  results_test = test_df %>%
    rename(home_team = Home_Tm, away_team = Away_Tm)%>%
    mutate(
      home_team = factor(home_team, levels = unik_teams),
      away_team = factor(away_team, levels = unik_teams),
      home_athome =1,
      away_athome = 0
    )
  tmp_df <- data.frame(Home_Winner = results_train$Home_Winner, Away_Winner = results_train$Away_Winner)
  
  tmp_df$home_team <- data.frame(team = results_train$home_team, at_home = results_train$home_athome, pitcher_era = results_train$Home_Pitcher_ERA)
  
  tmp_df$away_team <- data.frame(team = results_train$away_team, at_home = results_train$away_athome, pitcher_era = results_train$Away_Pitcher_ERA)
  
  fit <-
  BTm(
    outcome = cbind(Home_Winner, Away_Winner),  
    player1 = home_team, player2 = away_team,
    formula = ~ team + at_home + pitcher_era,
    refcat = "ARI",
    id = "team",
    data = tmp_df) 
  
  abil_mat = BTabilities(fit)
  abil = abil_mat[,"ability"]
  beta_home = coef(fit)["at_home"]
  beta_era = coef(fit)["pitcher_era"]
  
  home = as.character(results_test$home_team)
  away = as.character(results_test$away_team)
  difference_in_abil = abil[home] - abil[away]
  difference_era = results_test$Home_Pitcher_ERA - results_test$Away_Pitcher_ERA
  
  phat = plogis(difference_in_abil + beta_home + difference_era * beta_era) 
  
  cv_log = rbind(cv_log,
                 data.frame(iter = r,
                            brier=brier(results_test$Home_Winner, phat),
                            logloss=logloss(results_test$Home_Winner, phat)))
}

```

```{r}
summary(fit)


cv_log %>%
  summarize(mean_brier = mean(brier),
            mean_logloss = mean(logloss))
```




```{r}###ab
results <- games_with_pitchers %>% 
  rename(home_team = Home_Tm, away_team = Away_Tm) %>% 
  mutate(
    home_team = factor(home_team, levels = unik_teams), 
    away_team = factor(away_team,levels = unik_teams),
    home_athome = 1,
    away_athome = 0) %>% 
  select(Date, game_id, home_team, away_team, Home_Winner, Away_Winner, home_athome, away_athome, Home_Pitcher_ERA, Away_Pitcher_ERA)

results_train = results %>%
  slice(train_idx)

results_test = results %>%
  slice(-train_idx)
```

```{r}###
tmp_df <- data.frame(Home_Winner = results_train$Home_Winner, Away_Winner = results_train$Away_Winner)

tmp_df$home_team <- data.frame(team = results_train$home_team, at_home = results_train$home_athome, pitcher_era = results_train$Home_Pitcher_ERA)

tmp_df$away_team <- data.frame(team = results_train$away_team, at_home = results_train$away_athome, pitcher_era = results_train$Away_Pitcher_ERA)
```

```{r}###
fit <-
  BTm(
    outcome = cbind(Home_Winner, Away_Winner),  
    player1 = home_team, player2 = away_team,
    formula = ~ team + at_home + pitcher_era,
    refcat = "BOS",
    id = "team",
    data = tmp_df) 

summary(fit)
```

```{r}###
lambda_hat <- BTabilities(fit)
lambda_home <- coef(fit)["at_home"]
```

```{r}###
Home_Win_Prob <- function(home_team, away_team, home_pitcher_era, 
                          away_pitcher_era) {
  diff_latent_strengths <- 
    lambda_hat[home_team, "ability"] - lambda_hat[away_team, "ability"]
  
  diff_pitcher_eras <- (home_pitcher_era - away_pitcher_era)
  
  lambda_pitcher_era <- coef(fit)["pitcher_era"]
  
  return(1/(1 + exp(-1 * (diff_latent_strengths + lambda_home + (diff_pitcher_eras*lambda_pitcher_era)))))
}
```

```{r}###
brier <- function(y, phat){
  return(mean( (y - phat)^2 ))
}

logloss <- function(y, phat){
  
  if(any(phat < 1e-12)) phat[phat < 1e-12] <- 1e-12
  if(any(phat > 1-1e-12)) phat[phat > 1-1e-12] <- 1-1e-12
  return(-1 * mean( y * log(phat) + (1-y) * log(1-phat)))
}

probs_test <- results_test %>% 
    mutate(home_win_prob = Home_Win_Prob(home_team, away_team, Home_Pitcher_ERA, Away_Pitcher_ERA))

brier(probs_test$Home_Winner, probs_test$home_win_prob)
logloss(probs_test$Home_Winner, probs_test$home_win_prob)
```

